#% text_encoding=iso8859_1
:roos_image_compare_master_dialog	Vergelijk Images (Zender)
:top_info				
Vul de poort en de host in waar de Ontvanger op luistert. Bij host kan de naam 
of ip-nummer van de machine worden gebruikt. Gebruik 'localhost' voor 
de huidige machine.

Zorg ervoor dat hetzelfde filter bestand wordt gebruikt voor Zender
als Onvanger, anders kan het resultaat verwarrend zijn.

Start eerst de Ontvanger.
:port_lbl				Poort
:host_lbl				Host
:filter_lbl				Filter
:report_lbl				Rapport
:report_format_lbl			Rapport formaat
:compare_exemplars_lbl			Vergelijk Exemplars
:compare_mixins_lbl			Vergelijk Mixins
:compare_globals_lbl			Vergelijk Globalen
:compare_messages_lbl			Vergelijk Message Handlers
:start_lbl				Start
:start_tt				Start de vergelijking. Dit kan enkele minuten duren.
:stop_lbl				Stop
:stop_tt				Onderbreek de actie. Er wordt geen rapport gemaakt.
:close_lbl				Sluit
:pick_filter_title			Kies het filter voor de vergelijking:
:pick_report_title			Kies een bestandnaam voor het rapport
:no_valid_host				De opgegeven Host naam kan niet worden gevonden
:filter_not_readable			Het opgegeven bestand voor de filter is niet te lezen.
:report_not_creatable			Het opgegeven bestand voor de rapportage is niet aan te maken.
:communication_was_interrupted		De communicatie werd onderbroken.
:writing_report				Rapportage wordt geschreven...
:report_end				Rapportage is gereed.
:ready					Druk op Start om te beginnen
:slave_not_listening			De Ontvanger is niet aan het luisteren op de opgegeven poort.#nStart eerst de Ontvanger.
