#% text_encoding=iso8859_1
:roos_image_compare_slave_dialog	Vergelijk Images (Ontvanger)
:top_info				Vul de poort in waar deze Ontvanger gaat luisteren naar de Zender. Gebruik 
geen standaard poortnummer (1-1023), om problemen te voorkomen.

Zorg ervoor dat hetzelfde filter bestand wordt gebruikt voor Zender
als Onvanger, anders kan het resultaat verwarrend zijn.

Start eerst deze Ontvanger, dan de Zender.
:port_lbl				Poort
:host_lbl				Host
:filter_lbl				Filter
:report_lbl				Rapport
:start_lbl				Start
:start_tt				Start de vergelijking. Dit kan enkele minuten duren.
:stop_lbl				Stop
:stop_tt				Onderbreek de actie. Er wordt geen rapport gemaakt.
:close_lbl				Sluit
:pick_filter_title			Kies het filter voor de vergelijking:
:no_valid_host				De opgegeven Host naam kan niet worden gevonden
:filter_not_readable			Het opgegeven bestand voor de filter is niet te lezen.
:communication_was_interrupted		De communicatie werd onderbroken.
:ready					Druk op Start om te beginnen
:waiting_for_connection			Wachten op verbinding.....