#% text_encoding=iso8859_1
:roos_image_compare_master_dialog	Compare Images (Sender)
:top_info				
Enter the port and host where the Receiver is listening. Either use the the name
or the ip-number of the machine. Use 'localhost' for
the the current machine.

Make sure the Sender and Receiver use the same filter file. Otherwise
the result could be confusing.

First start the Receiver.
:port_lbl				Port
:host_lbl				Host
:filter_lbl				Filter
:report_lbl				Report
:report_format_lbl			Report format
:compare_exemplars_lbl			Compare Exemplars
:compare_mixins_lbl			Compare Mixins
:compare_globals_lbl			Compare Globals
:compare_messages_lbl			Compare Message Handlers
:start_lbl				Start
:start_tt				Start comparing. This may take some minutes.
:stop_lbl				Stop
:stop_tt				Interrupt the action. No report is written.
:close_lbl				Close
:pick_filter_title			Pick the filter for comparing:
:pick_report_title			Pick the filename for the report
:no_valid_host				The Host name can not be found
:filter_not_readable			The filter filename can not be read.
:report_not_creatable			The report filename can not be created.
:communication_was_interrupted		Communicatie is interrupted.
:writing_report				Report is being written...
:report_end				Report is finished.
:ready					Press Start to begin
:slave_not_listening			The Receiver is not listening at the given port.#nFirst start the Receiver.
