#% text_encoding=iso8859_1
:roos_image_compare_slave_dialog	Compare Images (Receiver)
:top_info				Enter the port the Receiver is listening to the Sender. Do not 
use a standard port (1-1023) to avoid problems.

Make sure the Sender and Receiver use the same filter file. Otherwise
the result could be confusing.

First start the Receiver.
:port_lbl				Port
:host_lbl				Host
:filter_lbl				Filter
:report_lbl				Report
:start_lbl				Start
:start_tt				Start the comparison. This may take several minutes.
:stop_lbl				Stop
:stop_tt				Interrupt the action. No report is made.
:close_lbl				Close
:pick_filter_title			Pick the filter for comparing:
:no_valid_host				The Host name van not be found
:filter_not_readable			The filter filename can not be read.
:communication_was_interrupted		ommunication is interrupted.
:ready					Press Start to begin
:waiting_for_connection			Waiting for connection.....